CREATE TABLE T_XBBNHFN_CUSTOMERDETAILS(CUSTOMER_ID NUMBER,CUSTOMER_NAME VARCHAR(15),CUSTOMER_PHNO VARCHAR(10),
CUSTOMER_ADDRESS VARCHAR(40),CUSTOMER_EMAIL VARCHAR(30),CUSTOMER_LOCATION VARCHAR(15),CUSTOMER_USERNAME VARCHAR(10));
 from t_xbbnhfn_customerdetails;
insert into T_XBBNHFN_CUSTOMERDETAILS values(20,'Vidya','0987654321','nanganallur','abc@gmail.com','nanganallur','Vidya123');
insert into T_XBBNHFN_CUSTOMERDETAILS values(30,'Radha','1987654321','tnagar','bbc@gmail.com','tnagar','Radha123');