CREATE TABLE T_XBBNHFN_CUSTOMERDETAILS(CUSTOMER_ID NUMBER,CUSTOMER_NAME VARCHAR(15),CUSTOMER_PHNO VARCHAR(10),
CUSTOMER_ADDRESS VARCHAR(40),CUSTOMER_EMAIL VARCHAR(30),CUSTOMER_LOCATION VARCHAR(15),CUSTOMER_USERNAME VARCHAR(10));
select * from t_xbbnhfn_customerdetails;