CREATE TABLE T_XBBNHFN_LOGINDETAILS(type number,username varchar(8),password varchar(15));
INSERT INTO T_XBBNHFN_LOGINDETAILS VALUES(1,'GAYATHRI','GATHUU');
INSERT INTO T_XBBNHFN_LOGINDETAILS VALUES(2,'Sam12345','Sam');
SELECT DISTINCT CUSTOMER_ID FROM T_XBBNHFN_CUSTOMERDETAILS,T_XBBNHFN_LOGINDETAILS WHERE USERNAME='Vidya123';
SELECT DISTINCT SP_ID FROM T_XBBNHFN_PROVIDERDETAILS,T_XBBNHFN_LOGINDETAILS WHERE USERNAME='Ramesh12';
select * from T_XBBNHFN_LOGINDETAILS;
